name: Build
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ghidra:
          - "11.2"
          - "11.1.2"
          - "11.1.1"
          - "11.1"
          - "11.0.3"
          - "11.0.2"
          - "11.0.1"
          - "11.0"
          - "10.4"
          - "10.3.3"
          - "10.3.2"
          - "10.3.1"
          - "10.3"

    steps:
    - name: Clone Repository
      uses: actions/checkout@v4
  
    - name: Install Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Install Ghidra ${{ matrix.ghidra }}
      uses: antoniovazquezblanco/setup-ghidra@v2.0.6
      with:
        auth_token: ${{ secrets.GITHUB_TOKEN }}
        version: ${{ matrix.ghidra }}

    - name: Build
      run: gradle buildExtension

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Dragondance_Ghidra_${{ matrix.ghidra }}
        path: dist/*.zip
